### ISSUE TITLE
**Nxentry/definition:** "Clarify choice between NXentry & NXentry for application definitions

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#1125] opened 2022-06-23 19:47 UTC
**Nxentry/definition:** "This field is provided so that NXentry can be the overlay position in a NeXus data file for an application definition and its set of groups, fields, and attributes.

It is advised to use NXsubentry, instead, as the overlay position." https://manual.nexusformat.org/classes/base_classes/NXentry.html#nxentry

That seems to suggest to use NXsubentry in general/excessively, also for non-Multi-Method data - contrary to  https://manual.nexusformat.org/rules.html#nxsubentry-or-multi-method-data ?

_Originally posted by @gerrit-guenther in https://github.com/nexusformat/definitions/issues/886#issuecomment-804880586_

**Comment by prjemian** [comment] 2022-06-23 19:52
Not necessary to resolve this for release of NXDL now.

**Comment by soph-dec** [comment] 2022-06-28 09:49
This is a duplicate of #1030 .

**Closed** 2022-06-29 00:14 UTC
Labels: duplicate, wontfix, documentation, code camp
