### ISSUE TITLE
incremental builds of manual broken

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#360] opened 2015-01-03 16:23 UTC
Since converting to cmake, incremental builds of the manual are now broken.  This capability should be restored.

**Comment by prjemian** [comment] 2015-01-07 16:55
did not work for me (on Linux)

    mkdir build
    cd build
    cmake ..
    make
    # now edit contributed/NXcanSAS.nxdl.xml, make a change in one of the <doc> elements
    make
    firefox manual/build/html/classes/contributed_definitions/NXcanSAS.html

This shows the original documentation, without change to the edited <doc> element.

Usually, I edit/test using Windows and run a Sphinx build within a shell from eclipse.  Not sure how this will work with cmake.

**Comment by FreddieAkeroyd** [comment] 2015-01-07 19:22
OK, the rst is rebuild from the NXDL but there is no dependency of the finished manual on the rst and so CMake does not re-run sphinx. Did you add explicit dependencies previously with the Makefiles?

On windows, you could run cmake with a different generator (mingw or nmake) and then execute a "make" from eclipse, or I think CMake can generate eclipse project files too.

**Comment by prjemian** [comment] 2015-01-13 19:50
Yes.  That was done with <definitions>/manual/source/classes/{base_classes,applications,contributed_definitions}Makefile

**Comment by prjemian** [comment] 2015-01-20 19:30
Not sure I get the cmake syntax yet.  Perhaps this in each  <defs>/manual/source/classes/{base_classes,applications,contributed_definitions}/CMakeLists.txt file, inside the foreach(VAR ${SRCs}) loop:
	    add_custom_target(${RST} DEPENDS ${SRCDIR}/${VAR})

or is this already included at this line?
	    DEPENDS ${SRCDIR}/${VAR} ${NXDL2RST}

**Comment by prjemian** [comment] 2015-01-20 19:41
That did not fix it.  Following the test procedure above (editing the NXcanSAS NXDL), the <defs>/build/manual/source/classes/contributed_definitions/NXcanSAS.rst file is properly rebuilt but Sphinx does not rebuild the associated HTML page.

Also, I find the <defs>/build/manual/source/classes/contributed_definitions/NXcanSAS.nxdl.xml (the *copy* in the Sphinx .rst source directory) has the original content from the time of the "cmake .." step.

**Comment by prjemian** [comment] 2015-01-20 19:47
Also, it seems that ALL the NXDL files are being rebuilt into .rst files for every incremental build.  This is not ready yet.

**Comment by prjemian** [comment] 2015-03-11 19:40
Even though the .rst files are rebuilt, Sphinx does not get the triggers to rebuild the PDF and HTML.

There are several things wrong with the cmake configuration.  Still debating whether to regress and pursue issue #391 or try to fix the cmake configuration, which is the long-term plan.

**Comment by prjemian** [comment] 2015-03-11 19:41
When manual/build is removed, Sphinx triggers to rebuild the manual.  That's a starting point.

**Comment by eugenwintersberger** [comment] 2015-03-12 06:27
Hi Pete. As I mentioned in the last telecon: I will start to work on this during easter holidays I as  I am pretty occupied with other stuff right now. I guess I know where the problem is. 
Just one question: when you are using sphinx in a stand alone environment (without make, cmake, etc.) - does it perform incremental builds?

**Comment by prjemian** [comment] 2015-03-12 09:07
Sphinx uses make (Unix make, Windows make.bat).  Incremental builds are
routine.  This was a major improvement from docbook, which did not support
incremental builds.

**Comment by eugenwintersberger** [comment] 2015-05-28 07:47
This is fixed with merging the cmake_build branch.

**Closed by eugenwintersberger** 2015-05-28 07:47 UTC
