### ISSUE TITLE
Add a display precision attribute to fields

### ISSUE THREAD

**Issue by PeterC-DLS** [nexusformat/definitions#778] opened 2020-06-02 10:55 UTC
When real values are stored as floating point numbers, their displayed text can possess extraneous digits owing to the limited precision of the stored representation. This occurs frequently with decimal values that are integer multiples of negative powers of ten as their binary representations have recurring sequences of bits.

To aid reading software to display field values without seemingly higher precision, this proposal adds a `display_precision` attribute to that field. This attribute's value will be used to round the field's stored values to integer multiples before they are displayed.

**Comment by vasole** [comment] 2020-06-02 11:29
I have difficulties to accept that we should care about how many digits to display but not about if the axes of a plot have to be logarithmic or not.

**Comment by jonwright** [comment] 2020-06-02 11:53
This overlaps with the notion of scale-offset filters in hdf5 which seemed complicated, see:

http://hdf-forum.184993.n3.nabble.com/Question-about-Scale-offset-filter-td4025802.html

**Comment by rayosborn** [comment] 2020-06-02 13:13
I have some difficulty with this proposal. I can understand adding an attribute that represents the precision with which a value was measured, if that can be determined objectively, e.g., when using 100ns clock pulses to measure time. I don't believe, however, that NeXus files should be storing the number of decimal places if that's just for formatting displays. The g format does a good job of eliminating trailing digits caused by floating point precisions (1.00000000000000001, etc.).  I'm saying this partly because it would be a major headache for me to tailor the precision of every field that NeXpy reads.

**Comment by vasole** [comment] 2020-06-02 13:16
As far as I understand things, if one wants to provide the precision with which a VALUE was measured, one just needs to provide VALUE_errors.

**Comment by PeterC-DLS** [comment] 2020-06-02 14:03
Please consider that precision is **not** the same as measurement accuracy (or error). Also the measurement precision is potentially an additional attribute.

One use-case to consider is: demand values on a diffractometer arm. The user wants to step in fifths of a degree. The recorded values will all be close those multiples of fifths but get displayed as
```
['0.2000000000000000',  '0.4000000000000000',  '0.6000000000000001', '0.8000000000000000', '1.0000000000000000']
```
rather than the intended and, more useful,
```
['0.2, '0.4', '0.6', '0.8', '1.0']
```

**Comment by vasole** [comment] 2020-06-02 14:13
I repeat my previous comment. I have difficulties to accept that we should care about how many digits to display but not about if the axes of a plot have to be logarithmic or not.

If the floating point representation of 0.6 is 0.6000000000000001 you have to live with it or decide to use an appropriate format. How would you distinguish required positions 0.1, 0.2, 0.4 from reported encode values 0.0999999, 0.2000001,... Who tells you than when you asked 0.2 the hardware did not go somewhere else?

If you want to make a proper ASCII representation of something that does not have a proper ASCII representation you have chosen the wrong data type. In your case, to have an exact representation of what you have requested you would need to use 1/10th of degree as unit and use integers as data type.

**Comment by zjttoefs** [comment] 2020-06-02 15:04
For me the _errors does convey the information. Also, the way this addresses the problem, I see some unwanted overlap with valid figures for measurement precision. That could confuse people and result in some misuse.
Ray's mentioned the format string. A proposal in that direction would go around that.

**Comment by jonwright** [comment] 2020-06-02 16:06
Could it work to store the integer (hardware values) and the scaling_factor from NXdata ?

**Comment by PeterC-DLS** [comment] 2020-06-02 17:45
@jonwright A scale and offset filter will not work as the datasets are converted back on read. The datasets are not the "signal" but the axes so `NXdata` is not suitable.

**Comment by PeterC-DLS** [comment] 2020-06-02 17:52
The error is not the issue: for example, how would you display 3.14159&pm;0.000093

**Comment by vasole** [comment] 2020-06-02 18:14
Following that uncertainty the correct way to display it is 3.14159 +/- 0.00009

**Comment by PeterC-DLS** [comment] 2020-06-02 20:31
And 2.87585&pm;0.00019?

**Comment by rayosborn** [comment] 2020-06-02 20:44
These things are a matter of taste or style. So I guess the question is whether you want to dictate that decision when you write the file, or allow people to choose when they read the file. Personally, I don't think it's our job to decide.

**Comment by vasole** [comment] 2020-06-02 22:03
In my Physics course we were only allowed to provide two digits in the uncertainty if (zeros stripped) they were up to "25". In your case, you would be allowed to write the number as you have written it. That rule solves problems like 2.35 +/- 0.14 being rounded to 2.4 +/- 0.1 A lazy programmer would just round the uncertainty to two significant digits and then adjust the actual value to match. In your case, if your uncertainty is already smaller than the limit of the floating point representation of the number that means you are already using the wrong data type. So yes, 1) the VALUE_errors can be used for display purposes when it matters and 2) if we already decided we would not enter into more critical details like how to display NXdata axes (linear, logarithmic) or colormap normalization (linear, logarithmic) I do not see why we should endorse this proposal. 

As suggested to us, create your own APPLICATION_display_precision attribute and enjoy.

**Comment by PeterC-DLS** [comment] 2020-06-03 07:59
The precision of a measurement (or some value on a positioner) is extra information not intrinsic to the magnitude of its error. The last value was the electron to tau mass ratio (without the powers of ten) listed on [CODATA](https://physics.nist.gov/cgi-bin/cuu/Value?mesmtau#mid). I don't think it is purely aesthetic.

**Comment by mkoennecke** [comment] 2020-06-03 14:53
I feel that this is out of the scope of NeXus. NeXus takes care to provide the data and errors, when known. How to represent the data in a plot should be left to the implementor of the plotting tool. Moreover, can we know the display precision when we write the file? Often, the errors on which the display precision necessarily depends gets calculated only in data reduction.

**Comment by prjemian** [comment] 2020-06-03 15:37
The issue is in scope since enabling simple plotting is one of the [basic motivations](https://manual.nexusformat.org/motivations.html#simple-plotting) of the NeXus standard.

For debate in this issue is the level of detail NeXus describes for the plot configuration.  As @vasole points out, we have already decided axis style is not within the standard.  Is there a clear limit to what details are in scope?

**Comment by vasole** [comment] 2020-06-03 16:09
Concerning the plotting, and to my regret (https://github.com/nexusformat/NIAC/issues/29), NIAC2018 was fairly clear:  NeXus is about how to find and annotate the data to be plotted but not about to describe how the data is to be plotted. Even I voted in favor! @benajamin suggested to use a single application specific attribute for that purpose. At the ESRF we are going to follow that path (probably as early as end of this month). Our use case is mainly to provide information about when to using linear or logarithmic axes or colormap normalizations. My suggestion to @PeterC-DLS is either to follow the same approach using an application specific attribute or to make use of the associated uncertainty (if any) to decide how to display the data.

What follows is just a quote from https://www.nexusformat.org/NIAC2018Minutes.html

NXdata Plottype Attribute

This is about describing in more detail how the data is to be plotted. Color maps, linear or logarithmic axis etc. This could be achieved by having a plottype attribute at group level which contains keywords hinting at the intended presentation style.

After some discussion the NIAC came up with this proposal: NeXus is about how to find and annotate the data to be plotted but not to describe how the data is to be plotted.

Voting results: All in favor

**Comment by rayosborn** [comment] 2020-06-03 16:45
Writing as someone who develops general plotting software for NeXus data, this would be a minefield that I would rather not step into. For example, NeXpy uses Matplotlib to handle axis labelling. The Matplotlib package has an extensive code base that handles the precision with which axis labels are displayed. I presume most other plotting libraries have something similar. So far from making plotting easy, any attempt at honoring this attribute would require me to tinker with their low-level formatters for every single plot. As @vasole says, if this is important for Diamond, then it is quite possible for Diamond to add their own attributes  for use by their own applications but I am against adding it to the standard.

**Comment by prjemian** [comment] 2020-06-03 16:55
This part of the comment from @vasole :

> NeXus is about how to find and annotate the data to be plotted but not to describe how the data is to be plotted.

could be added to the manual in this section: https://manual.nexusformat.org/motivations.html?highlight=motivations#simple-plotting

Agree?

**Comment by vasole** [comment] 2020-06-03 17:06
@prjemian The minutes I quoted actually end with "This is to be placed into the documentation." I just stopped at the "All in favor" point.

The place you mention seems appropriate to me. However, that sentence was written in the NXdata context and perhaps one would expect to find it there too.

**Comment by PeterC-DLS** [comment] 2020-06-03 17:50
This attribute does not dictate anything about client programs using it to alter the way axes or their labels are generated or displayed - it's not specific to `NXdata` either. It is _optional_ and could be written by GDA (from a user or beamline setting).  The principal use-case is presenting the field's values as text in, for example, a table.

I wanted it to be language neutral and more general than just powers of ten so avoided a C-like format specifier.

**Comment by zjttoefs** [comment] 2020-06-04 08:48
Sounds like the format string would be closer to what you want, is easier to implement and would not confuse the issue with the measurement precision.

**Comment by jonwright** [comment] 2020-06-04 08:59
Experts, please correct this if this is wrong or if it goes against the spirit of your standard.

Scale and offset can be specified via NeXus Data Units. This allows you to remove the error.  
For me: this means I have found a place I could store digitized values correctly.

* 1.2.3.2. Rules for Storing Data Items in NeXus Files
    - NeXus Data Units : 
... `Values for the NeXus units must be specified in a format compatible with Unidata UDunits`  ...

There is a formal grammar for these, here: 
https://www.unidata.ucar.edu/software/udunits/udunits-2.1.24/udunits2lib.html#Syntax

Example in python:
```
from cfunits import Units
import numpy as np

def print_conversion( data, ufrom, uto ):
    print( "Conversion of (",ufrom.units, ") ---> (", uto.units,")" )
    print( data, " ---> ", Units.conform(data, ufrom, uto ))

data = np.array([2,4,6,8])
# scale
print_conversion( data, Units("microdegree") , Units("degree"))
# scale + offset
print_conversion( data, 
                  Units("microdegree @ 123.6"),
                  Units("degree"))
# a real encoder
encoder_step = Units("3 degree / %d"%round(17349.33*3) )
print_conversion( 1, encoder_step , Units("degree"))
print_conversion( 1, Units("degree"), encoder_step )
```
Outputs:
```
Conversion of ( microdegree ) ---> ( degree )
[2 4 6 8]  --->  [2.e-06 4.e-06 6.e-06 8.e-06]
Conversion of ( microdegree @ 123.6 ) ---> ( degree )
[2 4 6 8]  --->  [0.0001256 0.0001276 0.0001296 0.0001316]
Conversion of ( 3 degree / 52048 ) ---> ( degree )
1  --->  5.76391023670458e-05
Conversion of ( degree ) ---> ( 3 degree / 52048 )
1  --->  17349.333333333336
```
This was a pleasant surprise to me.  

For context, ESRF has a new control system that confuses IEEE floats with real numbers (https://gitlab.esrf.fr/bliss/bliss/-/issues/1487).

**Comment by PeterC-DLS** [comment] 2020-06-04 09:33
@jonwright I don't think many NeXus reading programs can parse complex expressions in units strings that include scale and offset - certainly, Dawn and GDA do not.

**Comment by jonwright** [comment] 2020-06-04 10:00
So just display the string as axis label ("microdegrees"). I don't think many packages can handle all the NXtransformations either. In passing: I note there is a typo recommending meters for angle here:

https://manual.nexusformat.org/nxdl-types.html#nx-angle

For the ESRF system someone to has chosen "pint" for units. This lets you have:
```
import fractions, decimal, pint
for number_type in [float, fractions.Fraction, decimal.Decimal]:
    ur = pint.UnitRegistry(non_int_type=number_type)
    steps = ur.parse_expression('360 degree / 200')
    print( number_type, (2*steps).to("degree")-3*ur.degree )
```
```
<class 'float'> 0.6000000000000001 degree
<class 'fractions.Fraction'> 3/5 degree
<class 'decimal.Decimal'> 0.6 degree
```
The problem you started with is using IEEE where you want a number in base 10.  No amount of duct tape will fix it.

**Comment by PeterC-DLS** [comment] 2020-06-04 10:30
It's a bit better than that: In Java, JSR 363 implementations can parse metric prefixes and simple expressions of compound units, and can convert quantities to desired units.

That typo should be easily fixed...

**Comment by PeterC-DLS** [comment] 2020-06-04 14:57
Note, the C-style conversion specifiers (`e`, `f`) do not control displayed precision but the number of digits to the right of the decimal point whereas the `g` specifier controls the number of significant digits and also removes trailing zeros. A simple example, `0.00000123` with `%.3g` becomes `1.23e-06`, and `%.3e` becomes `1.230e-06` and a value ten times larger (measured with the same precision of `1e-08`) becomes `1.23e-05` and `1.230e-05`, respectively.

**Comment by jonwright** [comment] 2020-06-07 06:21
When you say the hardware precision is 1e-8 do you mean the digitization was done on  a scale of 10pico units ? Or that you want to change from point to point because the instrument is autoranging ?

**Comment by PeterC-DLS** [comment] 2020-06-08 08:20
Yes. Variable precision is another matter but there's no reason the attribute couldn't be an array...

**Comment by zjttoefs** [comment] 2020-06-08 09:53
There are good reasons the attribute could not be an array of the same rank and dimension as the data.

**Comment by benajamin** [comment] 2020-08-23 20:38
I think @rayosborn hit the critical point here in that NeXus provides data for plotting, but doesn't (and shouldn't) give directions for how that plot should be presented.

**Comment by prjemian** [comment] 2020-09-09 16:14
Closing as "won't fix".

**Closed by prjemian** 2020-09-09 16:14 UTC
Labels: wontfix
